# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
  - _self_

infrastructure_name: "athena"

data_root: "${oc.env:PLG_GROUPS_STORAGE}/plggailpwmm/aszokalski/${project_name}"

fabric:
  accelerator: "cuda"

stages:
  capture:
    num_images_per_prompt: 5
    batch_size: 1
    num_workers: 1
    log_every_n_steps: 10

hydra:
  launcher:
    # 1. Athena Partition & Account
    partition: plgrid-gpu-a100
    account: plgmusicxai01-gpu-a100

    nodes: 1
    gpus_per_node: 0 #or 4
    tasks_per_node: 1 #or 4

    # Athena allows up to 16 CPUs and ~125GB RAM per A100 without extra charge.
    # We use 16 to speed up num_workers.
    cpus_per_task: 16
    mem_gb: 125

    # 3. Time Limits & Reliability
    timeout_min: 30  # 2 Hours (10 mins for testing)

    # If the job hits the 24h limit, Submitit will auto-requeue it 3 times.
    # Your .done marker logic ensures it resumes where it left off.
    max_num_timeout: 3
    signal_delay_s: 120

    # 4. Advanced SLURM Flags
    additional_parameters:
      # Send SIGUSR1 90 seconds before timeout to allow graceful shutdown
      signal: SIGUSR1@90
      requeue: true

      mail-user: szokalskiadam@gmail.com
      mail-type: BEGIN,END,FAIL

    # 5. Environment Setup
    setup:
      - source ./scripts/setup-plg.sh
      - conda activate diffusion-deep-dream-research-env