# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
  - _self_

infrastructure_name: "athena"

data_root: "${oc.env:PLG_GROUPS_STORAGE}/${oc.env:PLG_GROUP_NAME}/${oc.env:PLG_USERNAME}/${project_name}"

fabric:
  accelerator: "cuda"

stages:
  capture:
    num_images_per_prompt: 5
    batch_size: 1
    num_workers: 1
    log_every_n_steps: 10

hydra:
  launcher:
    partition: ${oc.env:PLG_SLURM_PARTITION}
    account: ${oc.env:PLG_SLURM_ACCOUNT}

    nodes: 1
    #Keep tasks per node the same as gpus (besides gpus = 0 for CPU jobs)
    gpus_per_node: 0
    tasks_per_node: 1

    # Athena allows up to 16 CPUs and ~125GB RAM per A100 without extra charge.
    cpus_per_task: 16
    mem_gb: 125
    
    timeout_min: 30

    max_num_timeout: 3
    signal_delay_s: 120

    additional_parameters:
      signal: SIGUSR1@90
      requeue: true

      mail-user: ${oc.env:NOTIFICATION_EMAIL}
      mail-type: BEGIN,END,FAIL

    # 5. Environment Setup
    setup:
      - source ./scripts/setup-plg.sh
      - conda activate diffusion-deep-dream-research-env