defaults:
   - deep_dream_schema
   - _self_

name: "deep_dream"
timesteps:
  - 0
  # - "active_timesteps"
  - "activity_peaks"


# This is only for small tests
# start_channel: 10
# end_channel: 30


see_through_schedule_noise: true

# REGULARISATION PARAMETERS
use_prior: true

total_variation_penalty_weight: 0.5
total_variation_penalty_weight_sae: 0

range_penalty_weight: 0.5
#range_penalty_weight_sae: 0.5

moment_penalty_weight: 0.0
moment_penalty_weight_sae: 0.5

gradient_smoothing_sigma_start: 0.5
gradient_smoothing_sigma_end: 0.0
gradient_smoothing_sigma_start_sae: 0.0

use_gradient_spectral_filtering: true  #old name: use_decorrelated_space
#use_gradient_spectral_filtering_sae: true

jitter_max: 1
#jitter_max_sae: 1

rotate_max: 5
#rotate_max_sae: 5

scale_max: 1.1
#scale_max_sae: 1.1


# OPTIMIZATION PARAMETERS
num_steps: 100
#num_steps_sae: 100

learning_rate: 0.05
#learning_rate_sae: 0.05

# For no prior:
seeds:
  - 1024
  - 1111
  - 4359
  - 3248
  - 1026
  
n_results: 5

log_every_n_steps: 10
intermediate_opt_results_every_n_steps: 10

timestep_analysis_results_dir: e0/Stage.timestep_analysis/multirun/2026-01-17/00-01-22/0
prior_results_dir: full_prior_generation/Stage.prior/multirun/2026-01-16/03-52-03/0